services:
  - type: web
    name: tkc-telegram-bot-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: APP_URL
        sync: false
      - key: WEBHOOK_PATH
        value: /webhook
      - key: WEBHOOK_URL
        sync: false
