
services:
  - type: web
    name: tkc-telegram-bot
    env: python
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: BOT_TOKEN
        sync: false
