services:
  - type: web
    name: tkc-telegram-bot
    env: python
    buildCommand: ""
    startCommand: gunicorn main:app
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: WEBHOOK_URL
        sync: false
