services:
  - type: web
    name: tkc-telegram-bot
    env: python
    buildCommand: ""
    startCommand: gunicorn wsgi:app
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
