BOT_TOKENS = {
    "shibanoy": "REPLACE_WITH_TOKEN_1",
    "giantjiw": "REPLACE_WITH_TOKEN_2",
    "p_tyretkc": "REPLACE_WITH_TOKEN_3",
    "tex_speed": "REPLACE_WITH_TOKEN_4"
}

OPENAI_API_KEY = "REPLACE_WITH_YOUR_OPENAI_API_KEY"